name: Python Doctest and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: 🧪 Doctest and Lint (Python 3.11)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install flake8 and pytest
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint with flake8 (basic syntax check)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run doctests
        run: |
          pytest --doctest-modules
